export const bagPrintConditions = [
  { printName: "bagprint1a", componentName: "BagPrint1A" },
  { printName: "bagprint2a", componentName: "BagPrint2A" },
  { printName: "bagprint3a", componentName: "BagPrint3A" },
  { printName: "bagprint4a", componentName: "BagPrint4A" },
  { printName: "bagprint4b", componentName: "BagPrint4B" },
  { printName: "bagprint5a", componentName: "BagPrint5A" },
  { printName: "bagprint6a", componentName: "BagPrint6A" },
  { printName: "bagprint7a", componentName: "BagPrint7A" },
  { printName: "bagprint10a", componentName: "BagPrint10A" },
  { printName: "bagprint11a", componentName: "BagPrint11A" },
  { printName: "bagprint12a", componentName: "BagPrint12A" },
  { printName: "bagprint13a", componentName: "BagPrint13A" },
  { printName: "bagprint14a", componentName: "BagPrint14A" },
  { printName: "bagprint15a", componentName: "BagPrint15A" },
  { printName: "bagprint16", componentName: "PrintDesign16" },
  { printName: "bagprint17", componentName: "PrintDesign17" },
  { printName: "bagprint18", componentName: "BagPrint18A" },
  { printName: "bagprint20", componentName: "BagPrint20A" },
  { printName: "jobbagstickera", componentName: "Jobbagsticker" },
  { printName: "jobbagsticker3", componentName: "Jobbagsticker3" },
];
