export const printConditions = [
    { printName: "summary 4", etpType: "print", componentName: "Summary4" },
    { printName: "summary 12", etpType: "print", componentName: "Summary12" },
    { printName: "tax invoice 1", etpType: "print", componentName: "TaxInvoice1" },
    { printName: "packing list 3", etpType: "print", componentName: "PackingList3" },
    { printName: "misc print 1", etpType: "print", componentName: "MiscPrint1" },
    { printName: "estimate print", etpType: "print", componentName: "EstimatePrint" },
    { printName: "retail", etpType: "print", componentName: "RetailPrint" },
    { printName: "retail1 print", etpType: "print", componentName: "RetailPrint" },
    { printName: "retail print 1", etpType: "print", componentName: "RetailPrint" },
    { printName: "detail print1 (p)", etpType: "print", componentName: "DetailPrint1" },
    { printName: "detail print k", etpType: "print", componentName: "DetailPrint1" },
    { printName: "detail print1 (l)", etpType: "print", componentName: "DetailPrint1" },
    { printName: "detail print r", etpType: "print", componentName: "DetailPrint1" },
    { printName: "detail print 11", etpType: "print", componentName: "DetailPrint11" },
    { printName: "invoice print", etpType: "print", componentName: "InvoicePrint" },
    { printName: "item wise print", etpType: "print", componentName: "ItemWisePrint" },
    { printName: "item wise print1", etpType: "print", componentName: "ItemWisePrint" },
    { printName: "item wise print2", etpType: "print", componentName: "ItemWisePrint" },
    { printName: "jewellery item wise", etpType: "print", componentName: "HallmarkItemWisePrint" },
    { printName: "jewellary invoice print", etpType: "print", componentName: "JewelleryInvoicePrint" },
    { printName: "Labour Bill", etpType: "print", componentName: "JewelleryInvoicePrint" },
    { printName: "labour bill", etpType: "print", componentName: "JewelleryInvoicePrint" },
    { printName: "detail print 12", etpType: "print", componentName: "DetailPrint12" },
    { printName: "export declaration form", etpType: "print", componentName: "ExportDeclarationForm" },
    { printName: "packing list", etpType: "print", componentName: "PackingList" },
    { printName: "summary 1", etpType: "print", componentName: "Summary1" },
    { printName: "jewellery tax invoice", etpType: "print", componentName: "JewelleryTaxInvoice" },
    { printName: "jewellery invoice", etpType: "print", componentName: "JewelleryInvoice" },
    { printName: "invoice print 2", etpType: "print", componentName: "InvoicePrint2" },
    { printName: "invoice print3", etpType: "print", componentName: "InvoicePrint3" },
    { printName: "invoice print4", etpType: "print", componentName: "InvoicePrint4" },
    { printName: "tax invoice", etpType: "print", componentName: "TaxInvoice" },
    { printName: "rough estimate", etpType: "print", componentName: "RoughEstimate" },
    { printName: "export", etpType: "print", componentName: "Export" },
    { printName: "export print", etpType: "print", componentName: "ExportPrint" },
    { printName: "export print 1", etpType: "print", componentName: "ExportPrint1" },
    { printName: "summary 13", etpType: "print", componentName: "Summary13" },
    { printName: "jewellery retail invoice c", etpType: "print", componentName: "JewelleryRetailInvoicePrintc" },
    { printName: "retail invoice print 4", etpType: "print", componentName: "RetailInvoicePrint4" },
    { printName: "invoice print r", etpType: "print", componentName: "InvoicePrint4Clone" },
    { printName: "manufacture mgt", etpType: "print", componentName: "ManufactureMgt" },
    { printName: "retail tax invoice", etpType: "print", componentName: "RetailTaxInvoice" },
    { printName: "summary print s", etpType: "print", componentName: "Summarys" },
    { printName: "summary 11", etpType: "print", componentName: "Summary11" },
    { printName: "packing list 1", etpType: "print", componentName: "PackingList1" },
    { printName: "retail invoice 2", etpType: "print", componentName: "RetailInvoice2_3" },
    { printName: "retail invoice 3", etpType: "print", componentName: "RetailInvoice2_3" },
    // Add more print conditions here
  ];
  export const excelConditions = [
    { printName: "sale format b", etpType: "excel", componentName: "ExcelToJsonDownload" },
    { printName: "sale format s", etpType: "excel", componentName: "ExcelToJsonDownloads" },
    { printName: "sale format a", etpType: "excel", componentName: "ExcelToJsonDownloadA" },
    { printName: "sale format j1", etpType: "excel", componentName: "ExcelToJsonDownloadJ1" },
    { printName: "detail print 11", etpType: "excel", componentName: "DetailPrint11Excel" },
  ];