export const printConditions = [
  {printName: 'customer daily statement', etpType: 'print', componentName: 'CustomerDailyStatement'},
  {printName: 'detail print1 (l)', etpType: 'print', componentName: 'DetailPrint1'},
  {printName: 'detail print1 (p)', etpType: 'print', componentName: 'DetailPrint1'},
  {printName: 'detail print2', etpType: 'print', componentName: 'DetailPrint2'},
  {printName: 'detail print3', etpType: 'print', componentName: 'DetailPrint3'},
  {printName: 'detail print4', etpType: 'print', componentName: 'DetailPrint4'},
  {printName: 'detail print 5', etpType: 'print', componentName: 'DetailPrint5'},
  {printName: 'detail print 6', etpType: 'print', componentName: 'DetailPrint6'},
  {printName: 'detail print 7', etpType: 'print', componentName: 'DetailPrint7'},
  {printName: 'detail print k', etpType: 'print', componentName: 'DetailPrint1'},
  {printName: 'detail print r', etpType: 'print', componentName: 'DetailPrint1'},
  {printName: 'detail print 8', etpType: 'print', componentName: 'DetailPrint8'},
  {printName: 'detail print 9', etpType: 'print', componentName: 'DetailPrint9'},
  {printName: 'detail print 10', etpType: 'print', componentName: 'DetailPrint10'},
  {printName: 'detail print 11', etpType: 'print', componentName: 'DetailPrint11'},
  {printName: 'detail print 12', etpType: 'print', componentName: 'DetailPrint12'},
  {printName: 'detail print k', etpType: 'print', componentName: 'DetailPrint1'},
  {printName: 'detail print r', etpType: 'print', componentName: 'DetailPrint1'},
  {printName: 'estimate print', etpType: 'print', componentName: 'EstimatePrint'},
  {printName: 'estimation print', etpType: 'print', componentName: 'EstimationPrint'},
  {printName: 'estimate print 1', etpType: 'print', componentName: 'EstimatePrint1'},
  {printName: 'export', etpType: 'print', componentName: 'Export'},
  {printName: 'export declaration form', etpType: 'print', componentName: 'ExportDeclarationForm'},
  {printName: 'export invoice', etpType: 'print', componentName: 'ExportInvoice'},
  {printName: 'export print', etpType: 'print', componentName: 'ExportPrint'},
  {printName: 'export print 1', etpType: 'print', componentName: 'ExportPrint1'},
  {printName: 'export print 2', etpType: 'print', componentName: 'ExportPrint2'},
  {printName: 'invoice print', etpType: 'print', componentName: 'InvoicePrint'},
  {printName: 'invoice print 10', etpType: 'print', componentName: 'InvoicePrint_10_11'},
  {printName: 'invoice print 11', etpType: 'print', componentName: 'InvoicePrint_10_11'},
  {printName: 'invoice print 12', etpType: 'print', componentName: 'InvoicePrint_12'},
  {printName: 'invoice print 2', etpType: 'print', componentName: 'InvoicePrint2'},
  {printName: 'invoice print r', etpType: 'print', componentName: 'InvoicePrint4Clone'},
  {printName: 'invoice print3', etpType: 'print', componentName: 'InvoicePrint3'},
  {printName: 'invoice print4', etpType: 'print', componentName: 'InvoicePrint4'},
  {printName: 'invoice print 5', etpType: 'print', componentName: 'InvoicePrint5'},
  {printName: 'invoice print 6', etpType: 'print', componentName: 'InvoicePrint6'},
  {printName: 'invoice print 7', etpType: 'print', componentName: 'InvoicePrint5'},
  {printName: 'invoice print 8', etpType: 'print', componentName: 'InvoicePrint8'},
  {printName: 'invoice print 9', etpType: 'print', componentName: 'InvoicePrint9'},
  {printName: 'item wise print', etpType: 'print', componentName: 'ItemWisePrint'},
  {printName: 'item wise print1', etpType: 'print', componentName: 'ItemWisePrint'},
  {printName: 'item wise print2', etpType: 'print', componentName: 'ItemWisePrint'},
  {printName: 'jewellary invoice print', etpType: 'print', componentName: 'JewelleryInvoicePrint'},
  {printName: 'jewellery invoice', etpType: 'print', componentName: 'JewelleryInvoice'},
  {printName: 'jewellery invoice 2', etpType: 'print', componentName: 'JewelleryInvoice2'},
  {printName: 'jewellery item wise', etpType: 'print', componentName: 'HallmarkItemWisePrint'},
  {printName: 'jewellery retail invoice c', etpType: 'print', componentName: 'JewelleryRetailInvoicePrintc'},
  {printName: 'jewellery tax invoice', etpType: 'print', componentName: 'JewelleryTaxInvoice'},
  {printName: 'Labour Bill', etpType: 'print', componentName: 'JewelleryInvoicePrint'},
  {printName: 'labour bill', etpType: 'print', componentName: 'JewelleryInvoicePrint'},
  {printName: 'labour summary print', etpType: 'print', componentName: 'LabourSummary'},
  {printName: 'misc print 1', etpType: 'print', componentName: 'MiscPrint1'},
  {printName: 'packing list', etpType: 'print', componentName: 'PackingList'},
  {printName: 'packing list 2', etpType: 'print', componentName: 'PackingList2'},
  {printName: 'packing list 1', etpType: 'print', componentName: 'PackingList1'},
  {printName: 'packing list 3', etpType: 'print', componentName: 'PackingList3'},
  {printName: 'packing list 4', etpType: 'print', componentName: 'PackingList4'},
  {printName: 'packing list 6', etpType: 'print', componentName: 'Packinglist6'},
  {printName: 'repair print', etpType: 'print', componentName: 'RepairPrint'},
  {printName: 'retail', etpType: 'print', componentName: 'RetailPrint'},
  {printName: 'retail invoice 2', etpType: 'print', componentName: 'RetailInvoice2_3'},
  {printName: 'retail invoice 3', etpType: 'print', componentName: 'RetailInvoice2_3'},
  {printName: 'retail invoice print 3', etpType: 'print', componentName: 'RetailInvoicePrint3'},
  {printName: 'retail invoice print 4', etpType: 'print', componentName: 'RetailInvoicePrint4'},
  {printName: 'retail invoice print 5', etpType: 'print', componentName: 'RetailInvoicePrint5'},
  {printName: 'retail invoice print 6', etpType: 'print', componentName: 'RetailInvoicePrint6'},
  {printName: 'retail invoice print 7', etpType: 'print', componentName: 'RetailInvoicePrint7'},
  {printName: 'retail print 1', etpType: 'print', componentName: 'RetailPrint'},
  {printName: 'retail tax invoice', etpType: 'print', componentName: 'RetailTaxInvoice'},
  {printName: 'retail1 print', etpType: 'print', componentName: 'RetailPrint'},
  {printName: 'rough estimate', etpType: 'print', componentName: 'RoughEstimate'},
  {printName: 'sale order', etpType: 'print', componentName: 'SaleOrder'},
  {printName: 'solitaire tax invoice', etpType: 'print', componentName: 'SolitaireTaxInvoice'},
  {printName: 'summary 1', etpType: 'print', componentName: 'Summary1'},
  {printName: 'summary 2', etpType: 'print', componentName: 'Summary2'},
  {printName: 'summary 3', etpType: 'print', componentName: 'Summary3'},
  {printName: 'summary 3 misc', etpType: 'print', componentName: 'Summary3'},
  {printName: 'summary 4', etpType: 'print', componentName: 'Summary4'},
  {printName: 'summary 5', etpType: 'print', componentName: 'Summary5'},
  {printName: 'summary 6', etpType: 'print', componentName: 'Summary6'},
  {printName: 'summary 7', etpType: 'print', componentName: 'Summary7'},
  {printName: 'summary 8', etpType: 'print', componentName: 'Summary8'},
  {printName: 'summary 9', etpType: 'print', componentName: 'Summary9'},
  {printName: 'summary 10', etpType: 'print', componentName: 'Summary10'},
  {printName: 'summary 11', etpType: 'print', componentName: 'Summary11'},
  {printName: 'summary 12', etpType: 'print', componentName: 'Summary12'},
  {printName: 'summary 13', etpType: 'print', componentName: 'Summary13'},
  {printName: 'summary print', etpType: 'print', componentName: 'SummaryPrint'},
  {printName: 'summary print s', etpType: 'print', componentName: 'Summarys'},
  {printName: 'summary in currency', etpType: 'print', componentName: 'SummaryInCurrency'},
  {printName: 'tax invoice', etpType: 'print', componentName: 'TaxInvoice'},
  {printName: 'tax invoice 1', etpType: 'print', componentName: 'TaxInvoice1'},
  {printName: 'tax invoice 3', etpType: 'print', componentName: 'TaxInvoice3'},
  {printName: 'tax invoice print 4', etpType: 'print', componentName: 'TaxInvoicePrint4'}, 
  {printName: 'tax invoice 5', etpType: 'print', componentName: 'TaxInvoice5'}, 
  {printName: 'tax invoice 6', etpType: 'print', componentName: 'TaxInvoice5'}, 
];

export const excelConditions = [
  { printName: "detail print 11", etpType: "excel", componentName: "DetailPrint11Excel"},
  { printName: "image zip file", etpType: "excel", componentName: "ImageExportExcel"},
  { printName: "packing list c", etpType: "excel", componentName: "PackingListCExcel"},
  { printName: "sale format b", etpType: "excel", componentName: "ExcelToJsonDownload"},
  { printName: "sale format s", etpType: "excel", componentName: "ExcelToJsonDownloads"},
  { printName: "sale format a", etpType: "excel", componentName: "ExcelToJsonDownloadA"},
  { printName: "sale format j1", etpType: "excel", componentName: "ExcelToJsonDownloadJ1"},
  { printName: "sale format r", etpType: "excel", componentName: "ExcelToJsonDownloadR"},
  { printName: "quotation format", etpType: "excel", componentName: "QuotationExcel"},
];

export const alterationArray = [
  {label:"alteration" ,evname: "RepairAlteration"},
  {label:"alteration receive" ,evname: "RepairAlterationReceive"},
]


